In [82]:
import torchvision
from torchvision.io.image import read_image
from torchvision.models.detection import ssdlite320_mobilenet_v3_large, SSDLite320_MobileNet_V3_Large_Weights
from torchvision.models.detection import ssd300_vgg16, SSD300_VGG16_Weights
from torchvision.utils import draw_bounding_boxes
from torchvision.transforms.functional import to_pil_image
import torch
from torchvision import transforms

import cv2 as cv
from PIL import Image
import numpy as np

import glob

In [73]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Step 1: Initialize model with the best available weights
weights = SSD300_VGG16_Weights.DEFAULT
# model = fasterrcnn_resnet50_fpn_v2(weights=weights, box_score_thresh=0.9)
model = ssd300_vgg16(weights=weights)
# model.to('cuda')
model = model.eval()
print("")

Downloading: "https://download.pytorch.org/models/ssd300_vgg16_coco-b556d3b4.pth" to C:\Users\evan_/.cache\torch\hub\checkpoints\ssd300_vgg16_coco-b556d3b4.pth
100.0%


In [79]:
# img = torch.tensor(read_image("dataset/train/PXL_20201107_214721193_jpg.rf.fb52dba4cf2addec4a3d4cc2e9fa527b.jpg"), device=device)
# filepath = "dataset/train/PXL_20201107_214721193_jpg.rf.fb52dba4cf2addec4a3d4cc2e9fa527b.jpg"
# pic = Image.open(filepath)
# pic = pic.resize((320, 320))
# print(pic)
# pic.show()

# pic = pic*255
# print(pic)
# picTorch = transforms.ToTensor()(pic).unsqueeze(0)
# picTorch.resize((320, 320))
# print(type(pic))
# trans = SSDLite320_MobileNet_V3_Large_Weights.COCO_V1.transforms()
# img = trans(pic2)
# print(pic.shape)
# img = read_image("dataset/train/IMG_6818_jpg.rf.4cf2cbc673b8173c113825f52ed30a16.jpg")
img = read_image("elephant.jpg")

# Step 2: Initialize the inference transforms
preprocess = weights.transforms()
# print(preprocess(pic).shape)

# Step 3: Apply inference preprocessing transforms
batch = [preprocess(img)]

# Step 4: Use the model and visualize the prediction
prediction = model(batch)[0]
labels = [weights.meta["categories"][i] for i in prediction["labels"]]

print(prediction["boxes"][:5])
print(labels[:5])

# get score for all the predicted objects
# pred_scores = prediction['scores'].detach().cpu().numpy()
# get all the predicted bounding boxes
# pred_bboxes = prediction['boxes'].detach().cpu().numpy()
# for i in range(len(prediction["scores"])):
#     if (prediction["scores"][i] > 0.9):
#         preds
# boxes = pred_bboxes[pred_scores >= 0.90].astype(np.int32)
# boxes = torch.tensor(boxes)
# labels = prediction['labels'][:len(boxes)]
scores = prediction['scores'][:5]
print(scores)

box = draw_bounding_boxes(img, boxes=prediction["boxes"][:5],
                          labels=labels[:5],
                          colors="red",
                          width=1, font_size=30)
im = to_pil_image(box.detach())
# im.show()


# image = cv.cvtColor(np.asarray(img), cv.COLOR_BGR2RGB)
# for i, box in enumerate(boxes):
#     color = COLORS[labels[i]]
#     cv.rectangle(
#         image,
#         (int(box[0]), int(box[1])),
#         (int(box[2]), int(box[3])),
#         color, 2
#     )
#     cv.putText(image, classes[i], (int(box[0]), int(box[1]-5)),
#                 cv.FONT_HERSHEY_SIMPLEX, 0.8, color, 2, 
#                 lineType=cv.LINE_AA)


tensor([[ 335.2332,    0.0000, 1166.3341,  630.0000],
        [ 191.2635,  234.5848,  356.4376,  390.4071],
        [1013.8081,   84.4025, 1189.9844,  517.3238],
        [ 120.9551,  205.6234,  214.7919,  375.5619],
        [ 127.1045,   22.7642,  624.1195,  370.3398]],
       grad_fn=<SliceBackward0>)
['elephant', 'elephant', 'elephant', 'elephant', 'elephant']
tensor([0.9923, 0.6977, 0.0790, 0.0649, 0.0582], grad_fn=<SliceBackward0>)


In [87]:
def save_cropped_objects (filepath, num_imgs, id):
	img = read_image(filepath)
	preprocess = weights.transforms()
	batch = [preprocess(img)]
	prediction = model(batch)[0]
	labels = [weights.meta["categories"][i] for i in prediction["labels"]]
	im = to_pil_image(box.detach())
	for i in range(num_imgs):
		print(prediction["boxes"])
		# im1 = im.crop(prediction["boxes"][i])
		# im1.save("cropped_imgs/" + str(id) + "_" + str(i) + ".jpg")

In [88]:
filepath = 'dataset/raw/train/'
for i, filename in enumerate(glob.glob(filepath + '*.jpg')):
	save_cropped_objects(filename, 5, i)

filepath = 'dataset/raw/test/'
for i, filename in enumerate(glob.glob(filepath + '*.jpg')):
	save_cropped_objects(filename, 5, i)

filepath = 'dataset/raw/valid/'
for i, filename in enumerate(glob.glob(filepath + '*.jpg')):
	save_cropped_objects(filename, 5, i)

tensor([[1221.5404, 1040.7366, 1536.0000, 1969.6663],
        [ 822.5319, 1409.1788,  950.5495, 1576.4170],
        [ 569.8260, 1719.4132,  976.0238, 2029.0206],
        [1181.4084, 1478.4995, 1516.5653, 2010.5194],
        [ 743.0154, 1705.9645, 1138.3199, 2032.8861],
        [ 677.5543, 1657.2581,  873.1884, 1983.6648],
        [ 763.0027, 1653.4701,  959.0185, 1980.7261],
        [1354.0586, 1435.9763, 1534.8417, 1663.3596],
        [1416.9476, 1467.4543, 1495.9919, 1554.3564],
        [1423.5701, 1512.0042, 1497.6173, 1599.8724],
        [ 698.9482, 1810.4294, 1010.4777, 2025.4773],
        [ 835.6030, 1634.5043, 1042.1556, 1975.4330],
        [1200.5667, 1553.4272, 1382.1244, 1968.4734],
        [1028.2148, 1550.9736, 1414.0001, 2026.9551],
        [1456.2340, 1510.2686, 1531.0409, 1607.3448],
        [1395.8367, 1437.9646, 1447.1752, 1489.5000],
        [1395.9387, 1531.5341, 1445.9716, 1595.5767],
        [1397.1465, 1477.7925, 1450.4115, 1541.8800],
        [ 429.8702, 1715.379